/**
 * 영문명 컬럼 표시용. 매핑이 없으면 심볼(대문자) 그대로 사용.
 * (거래소 API는 보통 한글명만 주므로, 주요 종목만 별도 영문 라벨)
 */
const COIN_ENGLISH: Record<string, string> = {
  BTC: "Bitcoin",
  ETH: "Ethereum",
  XRP: "XRP",
  SOL: "Solana",
  DOGE: "Dogecoin",
  ADA: "Cardano",
  AVAX: "Avalanche",
  DOT: "Polkadot",
  MATIC: "Polygon",
  POL: "Polygon",
  LINK: "Chainlink",
  ATOM: "Cosmos",
  LTC: "Litecoin",
  BCH: "Bitcoin Cash",
  ETC: "Ethereum Classic",
  XLM: "Stellar",
  ALGO: "Algorand",
  NEAR: "NEAR Protocol",
  APT: "Aptos",
  ARB: "Arbitrum",
  OP: "Optimism",
  SUI: "Sui",
  SEI: "Sei",
  TIA: "Celestia",
  INJ: "Injective",
  RUNE: "THORChain",
  FTM: "Fantom",
  SAND: "The Sandbox",
  MANA: "Decentraland",
  AXS: "Axie Infinity",
  CHZ: "Chiliz",
  ENJ: "Enjin Coin",
  GALA: "Gala",
  APE: "ApeCoin",
  BLUR: "Blur",
  IMX: "Immutable",
  WAXP: "WAX",
  GMT: "STEPN",
  JTO: "Jito",
  PYTH: "Pyth Network",
  W: "Wormhole",
  T: "Threshold",
  SUN: "SUN",
  TRX: "TRON",
  USDT: "Tether",
  USDC: "USD Coin",
  DAI: "Dai",
  BUSD: "Binance USD",
  SHIB: "Shiba Inu",
  PEPE: "Pepe",
  FLOKI: "Floki",
  BONK: "Bonk",
  WIF: "dogwifhat",
  JUP: "Jupiter",
  RNDR: "Render",
  FIL: "Filecoin",
  GRT: "The Graph",
  LDO: "Lido DAO",
  UNI: "Uniswap",
  AAVE: "Aave",
  MKR: "Maker",
  SNX: "Synthetix",
  CRV: "Curve",
  COMP: "Compound",
  SUSHI: "SushiSwap",
  ENS: "Ethereum Name Service",
  BAT: "Basic Attention Token",
  ZRX: "0x",
  KNC: "Kyber Network",
  YFI: "yearn.finance",
  SXP: "Solar",
  HBAR: "Hedera",
  VET: "VeChain",
  ICP: "Internet Computer",
  EGLD: "MultiversX",
  FLOW: "Flow",
  MINA: "Mina",
  ROSE: "Oasis",
  KAVA: "Kava",
  ZIL: "Zilliqa",
  ONE: "Harmony",
  CTK: "Shentu",
  STX: "Stacks",
  ORDI: "Ordinals",
  TON: "Toncoin",
  BNB: "BNB",
  CAKE: "PancakeSwap",
  CRO: "Cronos",
  FTT: "FTX Token",
  WAVES: "Waves",
  QTUM: "Qtum",
  IOST: "IOST",
  ONT: "Ontology",
  ZEC: "Zcash",
  DASH: "Dash",
  XMR: "Monero",
  RVN: "Ravencoin",
  SC: "Siacoin",
  STORJ: "Storj",
  ANKR: "Ankr",
  CVC: "Civic",
  OMG: "OMG Network",
  REQ: "Request",
  KSM: "Kusama",
  GLM: "Golem",
  OCEAN: "Ocean Protocol",
  BAND: "Band Protocol",
  NMR: "Numeraire",
  UMA: "UMA",
  REN: "Ren",
  BAL: "Balancer",
  CELR: "Celer Network",
  SKL: "Skale",
  NU: "NuCypher",
  KEEP: "Keep Network",
  MASK: "Mask Network",
  AUDIO: "Audius",
  CHR: "Chromia",
  COTI: "COTI",
  DENT: "Dent",
  HOT: "Holo",
  IOTA: "IOTA",
  NANO: "Nano",
  OXT: "Orchid",
  PUNDIX: "Pundi X",
  QNT: "Quant",
  RLC: "iExec RLC",
  STMX: "StormX",
  UOS: "Ultra",
  VTHO: "VeThor",
  WBTC: "Wrapped Bitcoin",
  WETH: "Wrapped Ethereum",
};

export function getCoinEnglishDisplayName(symbol: string): string {
  const key = symbol.trim().toUpperCase();
  return COIN_ENGLISH[key] ?? key;
}
